{% set name = "mercurial" %}
{% set version = "6.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 629604293df2be8171ec856bf4f8b4faa8e4305af13607dce0f89f74132836d6

build:
  number: 0
  # skip: true  # [py>311 and linux]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  commands:
    - hg --version
    - hg debuginstall

about:
  home: http://mercurial-scm.org
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Source control management tool
  description: |
    Mercurial is a distributed SCM tool written in Python.
    It is used by a number of large projects that require
    fast, reliable distributed revision control, such as
    Mozilla.

extra:
  recipe-maintainers:
    - paugier
