{% set version = "5.4" %}
{% set sha256 = "1df8d1978aefcbb65dc51e3666a452583f47aeaf3c5682e4c00a3b23cd805d6a" %}

package:
  name: mercurial
  version: {{ version }}

source:
  url: https://mercurial-scm.org/release/mercurial-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools  # [win]
  run:
    - python
    - setuptools  # [win]

test:
  commands:
    - hg --version

about:
  home: http://mercurial-scm.org
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Source control management tool
  description: |
    Mercurial is a distributed SCM tool written in Python.
    It is used by a number of large projects that require
    fast, reliable distributed revision control, such as
    Mozilla.

extra:
  recipe-maintainers:
    - ngoldbaum
    - paugier
