{% set version = "6.5.3" %}
{% set sha256 = "2cdc81fade129cf56b128417527f190ba72fd776567394ce54eed764e667e7d5" %}

package:
  name: mercurial
  version: {{ version }}

source:
  fn: mercurial-{{ version }}.tar.gz
  url: https://mercurial-scm.org/release/mercurial-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - setuptools  # [win]
  run:
    - python
    - setuptools  # [win]

test:
  commands:
    - hg --version
    - hg debuginstall

about:
  home: http://mercurial-scm.org
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Source control management tool
  description: |
    Mercurial is a distributed SCM tool written in Python.
    It is used by a number of large projects that require
    fast, reliable distributed revision control, such as
    Mozilla.

extra:
  recipe-maintainers:
    - paugier
